### ISSUE TITLE
Error in process filter: Wrong number of arguments: #[(proc char)

### ISSUE THREAD

**Issue by bjorntropf** [dieggsy/eterm-256color#7] opened 2018-03-27 14:43 UTC
In the last couple of days, I've started to get the following errors: (They always occur when switching from ansi-term to another buffer, but happen for other user actions as well):

> error in process filter: Wrong number of arguments: #[(proc char) "Æ=-	ÇXÈ ÇXÈ ... [char term-terminal-parameter term-terminal-previous-parameter term-height term-width tcr 72 0 1 term-goto 65 term-handle-deferred-scroll term-current-row term-down t 66 - 67 term-move-columns term-current-column 68 74 term-erase-in-display 75 term-erase-in-line 76 term-insert-lines 77 term-delete-lines 80 term-delete-chars 64 term-insert-spaces 104 4 108 nil 109 term-handle-colors-array 110 process-send-string format "[%s;%sR" term-horizontal-column 114 term-set-scroll-region term-scroll-start term-scroll-end term-insert-mode term-terminal-more-parameters term-terminal-previous-parameter-4 term-terminal-previous-parameter-3 term-terminal-previous-parameter-2 proc] 7], 3

(I've shortened any unprintable characters like ÇXÈ in the quote above with ...)

Even without a proper bisect, it looks like commit c3ca11635304ffd811a15e43ce5ca274dc3b84d8 could the culprit here. (Judging from the time the errors started to occur and the `(,proc ,char) in the code)

I'm using: GNU Emacs 25.3.3 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)

Please let me know if you need further information and thank you for providing this package!

**Comment by dieggsy** [comment] 2018-03-27 15:17
Huh. Thanks, I can reproduce. I'll look into this. For the time being, I've reverted to the commit just before that one.

**Comment by azzamsa** [comment] 2018-04-15 06:09
I spent hours investigating the root of this problem. removing all `ansi-term` config works for me. 

So I try add those config one by one. To see which one is the problem maker. Then removing `(add-hook 'term-mode-hook #'eterm-256color-mode)` was the answer.

My `ansi-term` freeze whenever I hit `backspace` and `C-x 1` and some other keys. It freeze and produce this error.

```
error in process filter: Wrong number of arguments: #[(proc char)
"Æ·(    ÇX\0È
ÇX\0È
V\0	V&\0É
S	S\"Ê Ë Ì
	ZWD\0
ZS\0	
YO\0
[S\0È	][Í\")Ë  SU?{\0Ì
	\\ Vv\0Î È
#y\0È	]Í\")ÏÈ	Ð \\Y\0ÎÐ È#\0	]!ÏÈ   
    ][!ÏÇ	    ^]Ð Z!Ñ     !Ò   !ÓÈ ]!ÔÈ	   
]!ÕÈ	]!ÖÈ	]!	×=)Í!
×=)Ø!\"ÈU
#ÇYð\0Ù#!$ÇYü\0Ù$!%ÇYÙ%!Ù
!Ù	!Ê Ú&ÛÜË TÝ T#\"Þ
S	S\"Í" [char term-terminal-parameter
term-terminal-previous-parameter term-height term-width tcr #s(hash-table
size 17 test eq rehash-size 1.5 rehash-threshold 0.8125 purecopy t data (72
6 65 45 66 87 67 125 68 149 71 156 74 167 75 171 76 175 77 181 80 187 64
193 104 199 108 210 109 221 110 272 114 289)) 0 1 term-goto
term-handle-deferred-scroll term-current-row term-down t -
term-move-columns term-current-column term-erase-in-display
term-erase-in-line term-insert-lines term-delete-lines term-delete-chars
term-insert-spaces 4 nil term-handle-colors-array process-send-string
format "[%s;%sR" term-horizontal-column term-set-scroll-region
term-scroll-start term-scroll-end term-insert-mode
term-terminal-more-parameters term-terminal-previous-parameter-4
term-terminal-previous-parameter-3 term-terminal-previous-parameter-2 proc]
7], 3
```

I thought it was because emacs25 can't handle `backspace` [properly](https://emacs.stackexchange.com/a/31421/11777). So I tried out Emacs 26.1. But turn out it was because [this package](https://www.reddit.com/r/emacs/comments/8b487b/emacs_pretest_261_rc1_is_out/dxdzexz/) :). 

Now I disabled this package and working with non-color prompt in ansi-term / multi-term.

**Comment by dieggsy** [comment] 2018-05-18 16:15
@azzamsa The revert should have fixed this for emacs<27

**Comment by azzamsa** [comment] 2018-05-18 21:12
I use this version from melpa. `eterm-256color 20180320.1141 `

**Comment by azzamsa** [comment] 2018-05-19 05:22
@dieggsy didn't melpa took/build from this repo ? or should I use certain commit version directly from this repo ?

**Comment by dieggsy** [comment] 2018-05-20 12:24
@azzamsa ah thanks, i've pushed a commit to try and make the changes reflect in melpa

**Comment by dieggsy** [comment] 2019-01-23 04:03
@azzamsa  @bjorntropf  sorry it took me.... almost a year to get this sorted. Let me know if 0f0dab497239ebedbc9c4a48b3ec8cce4a47e980 fixes this. I tested on emacs 25 and it seemed to get rid of the error.

**Comment by dieggsy** [comment] 2019-02-28 04:04
I'm assuming this is fixed, closing for now. Please comment if this is not the case.

**Closed as completed by dieggsy** 2019-02-28 04:04 UTC
